name: build-and-deploy (backend)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: |
            backend/package-lock.json

      - name: Verify lockfile exists
        run: |
          echo "Workspace: $(pwd)"
          ls -la
          ls -la backend
          test -f backend/package-lock.json && echo "Lockfile found" || (echo "Lockfile missing" && exit 1)

      - name: Install dependencies (backend)
        run: npm ci

      # Add build/test/deploy steps here as needed.
      # Example (uncomment if you add a build script):
      # - name: Build
      #   run: npm run build


