name: Deploy Backend to AWS Elastic Beanstalk

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20 with npm cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Removed cache to avoid lockfile path errors

      - name: Install dependencies (ci if lockfile, else install)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # Optional: Run migrations when RUN_MIGRATIONS secret is 'true'
      - name: Run Sequelize migrations (optional)
        env:
          NODE_ENV: production
          RUN_MIGRATIONS: ${{ secrets.RUN_MIGRATIONS }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          if [ "${RUN_MIGRATIONS}" = "true" ]; then
            echo "Running migrations..."
            npx sequelize db:migrate
          else
            echo "Skipping migrations"
          fi

      - name: Create deployment package
        run: |
          zip -r backend-${{ github.sha }}.zip . -x "node_modules/**" ".git/**" ".github/**" "uploads/**"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          application_name: ${{ secrets.EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
          version_label: backend-${{ github.sha }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: backend/backend-${{ github.sha }}.zip


